export const showHelp = (): void => {
  console.log('Usage: jwks [options]')
  console.log('Options:')
  console.log('  -c, --cert <path>  Path to the certificate file')
  console.log('  -k, --key <path>   Path to the private key file')
  console.log('  -o, --out <type>   Output type: jwks, public (pub), private (priv)')
  console.log('  -j, --jwks <path>  Path to the JWKS file')
  console.log('  -m, --make <num>   Make <num> self signed certificates with keys')
  console.log('  -a, --all <folder> Make jwks from all .pem and .key pairs in folder')
  console.log('  -v, --version      Show version number')
  console.log('  -h, --help         Show this help')
  console.log('Examples:')
  console.log('  $ jwks -c cert.pem -k cert.key')
  console.log('  $ jwks -c cert.pem -k cert.key -o pub')
  console.log('  $ jwks -c cert.pem -k cert.key -o pub,jwks')
  console.log('  $ jwks -a')
  console.log('  $ jwks -a ./certs')
	console.log('  $ jwks -a -o pub')
  console.log('  $ jwks -j jwks.json')
  console.log('  $ jwks -j jwks.json -o pub')
  console.log('  $ jwks -j jwks.json -o pub,priv')
  console.log('  $ jwks -m 3')
}